In [7]:
import numpy as np
import pandas as pd
from pycaret.classification import *
from sklearn.utils import resample

In [8]:
df = pd.read_excel(r'C:\Users\MrZoz\trail_1.xlsx')

train = resample(df, replace = True, n_samples = len(df))
test = df[~df.index.isin(train.index)]

df_train = train
df_test = test

df_train.fillna(-1, axis=1)
df_test.fillna(-1, axis=1)

# # df_train.to_excel('df_train.xlsx')
# # df_test.to_excel('df_test.xlsx')

,Label,X0,Y0,X1,Y1,X2,Y2,X3,Y3,X4,...,X505,Y505,X506,Y506,X507,Y507,X508,Y508,X509,Y509
0,Normal,1216.0,685.0,1216.0,684.0,1216.0,684.0,1216.0,683.0,1216.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,Normal,1310.0,671.0,1310.0,670.0,1310.0,669.0,1310.0,669.0,1310.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,Normal,971.0,641.0,970.0,641.0,967.0,641.0,966.0,641.0,959.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
5,Normal,930.0,610.0,929.0,609.0,928.0,608.0,928.0,607.0,928.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6,Normal,1314.0,668.0,1313.0,668.0,1311.0,668.0,1310.0,668.0,1308.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
10,Normal,1269.0,636.0,1270.0,636.0,1273.0,635.0,1274.0,635.0,1275.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
12,Normal,1177.0,609.0,1178.0,609.0,1179.0,609.0,1180.0,609.0,1181.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
14,Normal,1231.0,605.0,1231.0,605.0,1232.0,606.0,1233.0,606.0,1234.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
15,Normal,1324.0,686.0,1323.0,686.0,1321.0,686.0,1321.0,686.0,1316.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
21,Normal,374.0,537.0,373.0,537.0,373.0,537.0,372.0,537.0,370.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
22,Normal,621.0,555.0,620.0,555.0,619.0,555.0,619.0,555.0,618.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
24,Normal,746.0,557.0,747.0,557.0,750.0,557.0,752.0,557.0,759.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
33,Normal,1139.0,529.0,1133.0,527.0,1129.0,524.0,1122.0,523.0,1120.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
36,Normal,1312.0,666.0,1309.0,666.0,1304.0,667.0,1303.0,667.0,1297.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
42,Normal,998.0,549.0,998.0,549.0,996.0,549.0,996.0,549.0,993.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
43,Normal,797.0,377.5,811.0,365.5,814.0,368.5,823.0,374.5,813.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
58,Hungray,832.0,641.0,834.0,641.0,837.0,637.0,839.0,636.0,842.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
62,Normal,539.0,680.0,538.0,680.0,535.0,680.0,533.0,680.0,529.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
63,Hungray,750.0,520.0,746.0,519.0,722.0,515.0,714.0,513.0,685.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
66,Normal,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
67,Normal,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
69,Hungray,930.0,595.0,929.0,595.0,927.0,595.0,922.0,595.0,921.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
71,Normal,167.0,584.0,167.0,583.0,167.0,583.0,167.0,581.0,167.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
75,Normal,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
83,Normal,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
84,Normal,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
91,Abnormal,628.0,551.0,630.0,554.0,628.0,552.0,623.0,551.0,622.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
93,Hungray,382.0,533.0,382.0,533.0,372.0,531.0,368.0,530.0,356.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
94,Hungray,550.0,533.0,550.0,533.0,555.0,531.0,556.0,531.0,569.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
95,Abnormal,630.0,540.0,628.0,539.0,628.0,537.0,628.0,535.0,628.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
96,Abnormal,860.0,534.0,857.0,532.0,838.0,527.0,835.0,527.0,814.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
97,Hungray,1252.0,641.0,1207.0,648.0,1201.0,648.0,1156.0,648.0,1154.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
101,Abnormal,714.0,616.0,707.0,610.0,665.0,567.0,660.0,560.0,620.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
102,Hungray,787.0,654.0,789.0,650.0,802.0,624.0,804.0,621.0,811.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
103,Hungray,174.0,658.0,174.0,655.0,174.0,638.0,174.0,637.0,174.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
105,Hungray,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
108,Abnormal,1072.0,653.0,1072.0,653.0,1072.0,651.0,1071.0,650.0,1077.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
109,Abnormal,913.0,502.0,892.0,470.0,891.0,465.0,889.0,459.0,889.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
115,Abnormal,1094.0,683.0,1106.0,658.0,1109.0,649.0,1117.0,608.0,1118.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
116,Abnormal,990.0,673.0,1016.0,651.0,1025.0,643.0,1089.0,612.0,1093.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
119,Hungray,356.0,709.0,348.0,708.0,344.0,707.0,324.0,701.0,321.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
121,Hungray,90.0,543.0,75.0,556.0,61.0,574.0,59.0,577.0,54.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
129,Hungray,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
131,Abnormal,1205.0,601.0,1204.0,601.0,1204.0,598.0,1204.0,595.0,1204.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
132,Abnormal,1285.0,580.0,1283.0,581.0,1279.0,584.0,1278.0,584.0,1272.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
134,Abnormal,589.0,394.0,584.0,376.0,568.0,315.0,564.0,305.0,549.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
135,Abnormal,1005.0,518.0,1019.0,442.0,1020.0,437.0,1025.0,439.0,1030.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
136,Abnormal,636.0,538.0,642.0,527.0,682.0,484.0,684.0,490.0,684.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [ ]:
# df_train = pd.read_excel(r'C:\Users\MrZoz\df_train.xlsx')
# df_test = pd.read_excel(r'C:\Users\MrZoz\df_test.xlsx')

In [ ]:
# df_train = df_train.drop('Unnamed: 0', axis = 1)
# df_test = df_test.drop('Unnamed: 0', axis = 1)

In [12]:
ex = setup ( df_train ,test_data = df_test, target = 'Label', log_experiment = True, log_plots = True, use_gpu = True , 
              remove_perfect_collinearity= False , silent = True )

In [13]:
best = compare_models( )
best

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=6889, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
predict_model(best)

,X0,Y0,X1,Y1,X2,Y2,X3,Y3,X4,Y4,...,X508_not_available,Y508_413.0,Y508_not_available,X509_137.0,X509_not_available,Y509_414.0,Y509_not_available,Label,Label,Score
0,1216.0,685.0,1216.0,684.0,1216.0,684.0,1216.0,683.0,1216.0,682.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
1,1310.0,671.0,1310.0,670.0,1310.0,669.0,1310.0,669.0,1310.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0000
2,971.0,641.0,970.0,641.0,967.0,641.0,966.0,641.0,959.0,642.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
3,930.0,610.0,929.0,609.0,928.0,608.0,928.0,607.0,928.0,606.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,0.9999
4,1314.0,668.0,1313.0,668.0,1311.0,668.0,1310.0,668.0,1308.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
5,1269.0,636.0,1270.0,636.0,1273.0,635.0,1274.0,635.0,1275.0,634.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,0.9992
6,1177.0,609.0,1178.0,609.0,1179.0,609.0,1180.0,609.0,1181.0,610.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
7,1231.0,605.0,1231.0,605.0,1232.0,606.0,1233.0,606.0,1234.0,607.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0000
8,1324.0,686.0,1323.0,686.0,1321.0,686.0,1321.0,686.0,1316.0,686.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
9,374.0,537.0,373.0,537.0,373.0,537.0,372.0,537.0,370.0,537.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,0.8753
10,621.0,555.0,620.0,555.0,619.0,555.0,619.0,555.0,618.0,555.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
11,746.0,557.0,747.0,557.0,750.0,557.0,752.0,557.0,759.0,557.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,0.5820
12,1139.0,529.0,1133.0,527.0,1129.0,524.0,1122.0,523.0,1120.0,522.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
13,1312.0,666.0,1309.0,666.0,1304.0,667.0,1303.0,667.0,1297.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
14,998.0,549.0,998.0,549.0,996.0,549.0,996.0,549.0,993.0,551.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
15,797.0,377.5,811.0,365.5,814.0,368.5,823.0,374.5,813.0,377.5,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
16,832.0,641.0,834.0,641.0,837.0,637.0,839.0,636.0,842.0,635.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,0.9716
17,539.0,680.0,538.0,680.0,535.0,680.0,533.0,680.0,529.0,680.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,0.9285
18,750.0,520.0,746.0,519.0,722.0,515.0,714.0,513.0,685.0,511.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
19,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,364.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
20,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0000
21,930.0,595.0,929.0,595.0,927.0,595.0,922.0,595.0,921.0,595.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,0.9981
22,167.0,584.0,167.0,583.0,167.0,583.0,167.0,581.0,167.0,579.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,0.9999
23,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0000
24,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,364.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0000
25,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0000
26,628.0,551.0,630.0,554.0,628.0,552.0,623.0,551.0,622.0,553.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Abnormal,1.0000
27,382.0,533.0,382.0,533.0,372.0,531.0,368.0,530.0,356.0,529.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
28,550.0,533.0,550.0,533.0,555.0,531.0,556.0,531.0,569.0,531.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,0.9970
29,630.0,540.0,628.0,539.0,628.0,537.0,628.0,535.0,628.0,529.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,0.8230
30,860.0,534.0,857.0,532.0,838.0,527.0,835.0,527.0,814.0,517.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,0.8350
31,1252.0,641.0,1207.0,648.0,1201.0,648.0,1156.0,648.0,1154.0,648.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,1.0000
32,714.0,616.0,707.0,610.0,665.0,567.0,660.0,560.0,620.0,491.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,0.9968
33,787.0,654.0,789.0,650.0,802.0,624.0,804.0,621.0,811.0,606.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,0.9999
34,174.0,658.0,174.0,655.0,174.0,638.0,174.0,637.0,174.0,627.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
35,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,593.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
36,1072.0,653.0,1072.0,653.0,1072.0,651.0,1071.0,650.0,1077.0,649.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Abnormal,0.9953
37,913.0,502.0,892.0,470.0,891.0,465.0,889.0,459.0,889.0,471.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,0.9739
38,1094.0,683.0,1106.0,658.0,1109.0,649.0,1117.0,608.0,1118.0,603.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,0.8413
39,990.0,673.0,1016.0,651.0,1025.0,643.0,1089.0,612.0,1093.0,611.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,0.8951
40,356.0,709.0,348.0,708.0,344.0,707.0,324.0,701.0,321.0,699.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
41,90.0,543.0,75.0,556.0,61.0,574.0,59.0,577.0,54.0,590.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,1.0000
42,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,593.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0000
43,1205.0,601.0,1204.0,601.0,1204.0,598.0,1204.0,595.0,1204.0,591.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Abnormal,0.8676
44,1285.0,580.0,1283.0,581.0,1279.0,584.0,1278.0,584.0,1272.0,585.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,0.9965
45,589.0,394.0,584.0,376.0,568.0,315.0,564.0,305.0,549.0,246.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0000
46,1005.0,518.0,1019.0,442.0,1020.0,437.0,1025.0,439.0,1030.0,449.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,0.9997
47,636.0,538.0,642.0,527.0,682.0,484.0,684.0,490.0,684.0,496.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,1.0000

In [ ]:
evaluate_model(best)

In [ ]:
plot_model(best[0] , plot = 'confusion_matrix' )

In [ ]:
plot_model(best[0], plot = 'learning')

In [ ]:
plot_model(best[0], plot ='vc')

In [ ]:
save_model(best[0],'best_qda')

In [15]:
qda = create_model('qda', round = 4)

In [16]:
predict_model(qda)

,X0,Y0,X1,Y1,X2,Y2,X3,Y3,X4,Y4,...,X508_not_available,Y508_413.0,Y508_not_available,X509_137.0,X509_not_available,Y509_414.0,Y509_not_available,Label,Label,Score
0,1216.0,685.0,1216.0,684.0,1216.0,684.0,1216.0,683.0,1216.0,682.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
1,1310.0,671.0,1310.0,670.0,1310.0,669.0,1310.0,669.0,1310.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
2,971.0,641.0,970.0,641.0,967.0,641.0,966.0,641.0,959.0,642.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
3,930.0,610.0,929.0,609.0,928.0,608.0,928.0,607.0,928.0,606.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
4,1314.0,668.0,1313.0,668.0,1311.0,668.0,1310.0,668.0,1308.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
5,1269.0,636.0,1270.0,636.0,1273.0,635.0,1274.0,635.0,1275.0,634.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
6,1177.0,609.0,1178.0,609.0,1179.0,609.0,1180.0,609.0,1181.0,610.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
7,1231.0,605.0,1231.0,605.0,1232.0,606.0,1233.0,606.0,1234.0,607.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
8,1324.0,686.0,1323.0,686.0,1321.0,686.0,1321.0,686.0,1316.0,686.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
9,374.0,537.0,373.0,537.0,373.0,537.0,372.0,537.0,370.0,537.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
10,621.0,555.0,620.0,555.0,619.0,555.0,619.0,555.0,618.0,555.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
11,746.0,557.0,747.0,557.0,750.0,557.0,752.0,557.0,759.0,557.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
12,1139.0,529.0,1133.0,527.0,1129.0,524.0,1122.0,523.0,1120.0,522.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
13,1312.0,666.0,1309.0,666.0,1304.0,667.0,1303.0,667.0,1297.0,668.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
14,998.0,549.0,998.0,549.0,996.0,549.0,996.0,549.0,993.0,551.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
15,797.0,377.5,811.0,365.5,814.0,368.5,823.0,374.5,813.0,377.5,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
16,832.0,641.0,834.0,641.0,837.0,637.0,839.0,636.0,842.0,635.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,1.0
17,539.0,680.0,538.0,680.0,535.0,680.0,533.0,680.0,529.0,680.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
18,750.0,520.0,746.0,519.0,722.0,515.0,714.0,513.0,685.0,511.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
19,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,364.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
20,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
21,930.0,595.0,929.0,595.0,927.0,595.0,922.0,595.0,921.0,595.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
22,167.0,584.0,167.0,583.0,167.0,583.0,167.0,581.0,167.0,579.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
23,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
24,632.0,339.0,641.0,345.0,646.0,350.0,654.0,362.0,656.0,364.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Normal,1.0
25,707.0,562.0,705.0,562.0,704.0,562.0,700.0,562.0,697.0,562.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Normal,Hungray,1.0
26,628.0,551.0,630.0,554.0,628.0,552.0,623.0,551.0,622.0,553.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
27,382.0,533.0,382.0,533.0,372.0,531.0,368.0,530.0,356.0,529.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
28,550.0,533.0,550.0,533.0,555.0,531.0,556.0,531.0,569.0,531.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Normal,1.0
29,630.0,540.0,628.0,539.0,628.0,537.0,628.0,535.0,628.0,529.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
30,860.0,534.0,857.0,532.0,838.0,527.0,835.0,527.0,814.0,517.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
31,1252.0,641.0,1207.0,648.0,1201.0,648.0,1156.0,648.0,1154.0,648.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
32,714.0,616.0,707.0,610.0,665.0,567.0,660.0,560.0,620.0,491.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
33,787.0,654.0,789.0,650.0,802.0,624.0,804.0,621.0,811.0,606.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
34,174.0,658.0,174.0,655.0,174.0,638.0,174.0,637.0,174.0,627.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
35,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,593.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
36,1072.0,653.0,1072.0,653.0,1072.0,651.0,1071.0,650.0,1077.0,649.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
37,913.0,502.0,892.0,470.0,891.0,465.0,889.0,459.0,889.0,471.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
38,1094.0,683.0,1106.0,658.0,1109.0,649.0,1117.0,608.0,1118.0,603.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
39,990.0,673.0,1016.0,651.0,1025.0,643.0,1089.0,612.0,1093.0,611.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
40,356.0,709.0,348.0,708.0,344.0,707.0,324.0,701.0,321.0,699.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
41,90.0,543.0,75.0,556.0,61.0,574.0,59.0,577.0,54.0,590.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
42,1358.0,662.0,1357.0,657.0,1352.0,623.0,1350.0,619.0,1332.0,593.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Hungray,Hungray,1.0
43,1205.0,601.0,1204.0,601.0,1204.0,598.0,1204.0,595.0,1204.0,591.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
44,1285.0,580.0,1283.0,581.0,1279.0,584.0,1278.0,584.0,1272.0,585.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
45,589.0,394.0,584.0,376.0,568.0,315.0,564.0,305.0,549.0,246.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
46,1005.0,518.0,1019.0,442.0,1020.0,437.0,1025.0,439.0,1030.0,449.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Hungray,1.0
47,636.0,538.0,642.0,527.0,682.0,484.0,684.0,490.0,684.0,496.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,Abnormal,Normal,1.0

In [ ]:
evaluate_model(qda)

In [ ]:
# bilstm --> 77
# lstm --> 73
# RNN --> 75